### ISSUE TITLE
Unable to use CloudFront Function "Test" Feature with host.value

### ISSUE THREAD

**Issue by nCubed** [aws-samples/amazon-cloudfront-functions#19]
Doubt this is actually the correct place to report; maybe the repo owner could send this up the chain?

When using the property for the host header value in a CloudeFront Function and then testing with the "Test" tab, the test fails with the error:
```
The CloudFront function associated with the CloudFront distribution is invalid or could not run. TypeError: cannot get property "value" of undefined
```

Property used:  `event.request.headers.host.value`

The example event in the AWS documentation for [CloudFront Event Structure > Example Event](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-event-structure.html#functions-event-structure-example) shows this is a valid path and is also used in the [redirect-based-on-country](https://github.com/aws-samples/amazon-cloudfront-functions/blob/main/redirect-based-on-country/index.js) sample.

### Reproducible Example
Create a new function with the following basic structure:

```javascript
function handler(event) {
    var host = event.request.headers.host.value

    return request
}
```

Expected result: `Execution result status succeeded`

Actual result: `Execution result status failed`
Output: `The CloudFront function associated with the CloudFront distribution is invalid or could not run. TypeError: cannot get property "value" of undefined`

### Works in Practice
Oddly enough, the host value is evaluated correctly when CloudFront executes the function. Just seems to be an issue in the Test sandbox.

**Comment by brittandeyoung** [comment]
Does your test data contain a defined `host` header? 

From this error, it appears your request test data does not have a `host` header defined.

**Comment by nCubed** [comment]
Dunno 🤷🏼 This is 3 years later. Will close this out.
