### ISSUE TITLE
Cloudformation template  and CDK to deploy cloudfront function

### ISSUE THREAD

**Issue by orossant** [aws-samples/amazon-cloudfront-functions#4]
When will it possible to use cloudformation and/or CDK to deploy cloudfront function ?

**Comment by dbrown-git** [comment]
CloudFormation support is complete: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html
CDK Support is pending: https://github.com/aws/aws-cdk/pull/14511

**Comment by rodsjo** [comment]
Great work on CloudFront Functions! I've successfully deployed a CF Function with CloudFormation like this:

```yml
AddHTMLPostfixFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${ApplicationName}-add-html-postfix"
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          const hasExtension = /(.+)\.[a-zA-Z0-9]{2,5}$/
          const request = event.request
          const uri = request.uri

          // If the request does not have any extension, add '.html'
          if (uri && !uri.match(hasExtension)) {
            request.uri = `${uri}.html`
          }

          return request
        }
      FunctionConfig:
        Comment: "Adds .html postfix to viewer requests"
        Runtime: cloudfront-js-1.0
```

I did not find any documentation about how to set the `FunctionCode` property, but using inline code worked. It should have been support to point to a JS-file-path, like `CodeUri` and `Handler` or something like that
