### ISSUE TITLE
add-true-client-ip-header Runtime.HandlerNotFound

### ISSUE THREAD

**Issue by anvarkuchkartaev** [aws-samples/amazon-cloudfront-functions#9]
The function of add-true-client-ip-header is incomplete. 
Nodejs function cannot find the index.handler, because it is not exported. 

This behavior is seen in all currently supported runtimes:
Nodejs 14
Nodejs 12
Nodejs 10

Error message is below:

{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is undefined or not exported",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is undefined or not exported",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}

**Comment by dbrown-git** [comment]
CloudFront Functions does not use Node.JS as the JavaScript engine. The handler for CloudFront Functions must be:

function handler(event) {
//function logic
}
